host: 34.69.169.91 
user: dkube
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkIjoxNTgyMjY3ODE4LCJyb2xlIjoib3BlcmF0b3IiLCJ1c2VybmFtZSI6Im9jZGt1YmUifQ.Cz6EClW4Twb5AUXJUjhQV1-RXXH2hvcUjM5eX8xIras
jobname: auto
workspace: cellular
script: python cell-classification/model/train_frcnn.py -o simple -p /opt/dkube/input/annot.txt --hf --vf --rot --num_epochs 1
datasets:
  - name: cellular-train
    mountpath: /opt/dkube/input
models:
  - faster-rcnn
template: compare-test